import type { OptimizationRequest, OptimizationConfig } from "../types/api";

export const defaultOptimizationConfig: OptimizationConfig = {
  primary_objective: "minimize_truck_count",
  allow_unserved_fallback: true,
  minimize_truck_count: true,
  minimize_distance: true,
  minimize_time: true,
  minimize_depot_operation_time: false,
  objective_priority: [],
  hard_constraints: {
    capacity_limit: true,
    time_window: true,
    priority_eta: true,
    truck_category: true,
    no_split_order: false,
    depot_operation_window: true,
    max_route_duration: false,
    max_vehicle_working_time: true,
    max_total_distance_per_vehicle: false,
  },
  soft_constraints: {
    allow_unserved_orders: true,
    allow_overtime: true,
    capacity_limit: false,
    time_window: false,
    priority_eta: false,
    truck_category: false,
    depot_operation_window: false,
    max_route_duration: false,
    max_vehicle_working_time: false,
    max_total_distance_per_vehicle: false,
  },
  penalties: {
    unserved_order_penalty: 100000,
    late_arrival_penalty_per_minute: 100,
    priority_eta_penalty_per_minute: 200,
    overtime_penalty_per_minute: 50,
    depot_operation_window_penalty_per_minute: 50,
    capacity_violation_penalty: 0,
    activation_cost_vehicle: 10000,
    distance_weight: 1,
    time_weight: 1,
    depot_operation_time_weight: 1,
  },
  solver_options: {
    max_solver_seconds: 30,
    first_solution_strategy: "PATH_CHEAPEST_ARC",
    local_search_metaheuristic: "GUIDED_LOCAL_SEARCH",
  },
  max_route_duration_minutes: null,
  max_vehicle_working_time_minutes: 720,
  max_total_distance_per_vehicle_km: null,
  max_lateness_minutes: null,
};

export const sampleOptimizationRequest: OptimizationRequest = {
  dispatch_date: "2026-02-10",
  depot_id: "DPT001",
  depot_service_time_minutes: 30,
  orders: [
    {
      order_id: "ORD001",
      spbu_id: "SPBU001",
      product_type: "PERTALITE",
      demand_kl: 16,
      priority: true,
      eta: "08:00",
      service_time_minutes: 30,
      time_window_start: "08:00",
      time_window_end: "15:00",
    },
    {
      order_id: "ORD002",
      spbu_id: "SPBU002",
      product_type: "PERTALITE",
      demand_kl: 8,
      priority: true,
      eta: "09:00",
      service_time_minutes: 25,
      time_window_start: "09:00",
      time_window_end: "16:00",
    },
  ],
  available_trucks: [
    {
      truck_id: "TRK001",
      no_polisi: "B9101FMS",
      truck_type: "SMALL",
      truck_category: 2,
      capacity_kl: 8,
      start_depot_id: "DPT001",
      end_depot_id: "DPT001",
      shift_start: "06:00",
      shift_end: "18:00",
      compatible_product_types: ["PERTALITE", "PERTAMAX"],
      compartments: [{ compartment_id: "C1", capacity_kl: 8 }],
      status: "ACTIVE",
      not_available_from: null,
      not_available_to: null,
    },
    {
      truck_id: "TRK002",
      no_polisi: "B9102FMS",
      truck_type: "MEDIUM",
      truck_category: 3,
      capacity_kl: 16,
      start_depot_id: "DPT001",
      end_depot_id: "DPT001",
      shift_start: "06:00",
      shift_end: "18:00",
      compatible_product_types: ["PERTALITE"],
      compartments: [
        { compartment_id: "C1", capacity_kl: 8 },
        { compartment_id: "C2", capacity_kl: 8 },
      ],
      status: "ACTIVE",
      not_available_from: null,
      not_available_to: null,
    },
  ],
  optimization_config: defaultOptimizationConfig,
};
